# build with `conda build -c defaults -c conda-forge .`

package:
  name: 'nionswift'
  version: '16.11.0'

source:
  git_rev: 16.11.0
  git_url: https://github.com/nion-software/nionswift.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False
  entry_points:
    - nionswift = nion.swift.command:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.11
    - nionutils >=4.11.0,<5.0
    - niondata >=15.6.2,<16.0
    - nionui >=7.1.0,<8.0
    - nionswift-io >=15.2,<16.0
    - scipy
    - numpy >=2.0,<3.0
    - h5py
    - imageio >=2.19.0
    - pytz
    - tzlocal
    - pillow

test:
  imports:
    - nion.swift
    - nion.swift.model
    - nion.swift.test
    - nionui_app.nionswift
    - nionswift_plugin.none
    - nionlib
    - nion.typeshed

about:
  home: https://github.com/nion-software/nionswift
  license: GPL-3.0
  summary: Nion Swift image and data processing application.
  description: "An application for image and data processing."

extra:
  recipe-maintainers:
    cmeyer
