# build with `conda build -c defaults -c conda-forge .`

package:
  name: 'nionswift'
  version: '0.14.8'

source:
  git_rev: 0.14.8
  git_url: https://github.com/nion-software/nionswift.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False
  entry_points:
    - nionswift = nion.swift.command:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6
    - nionutils >=0.3.20
    - niondata >=0.13.6
    - nionui >=0.3.21
    - nionswift-io >=0.13.0
    - scipy
    - numpy
    - h5py
    - imageio
    - pytz
    - tzlocal
    - pillow

test:
  imports:
    - nion.swift
    - nion.swift.model
    - nion.swift.test
    - nionui_app.nionswift
    - nionswift_plugin.none
    - nionlib
    - nion.typeshed

about:
  home: https://github.com/nion-software/nionswift
  license: GPL-3.0
  summary: Nion Swift image and data processing application.
  description: "An application for image and data processing."

extra:
  recipe-maintainers:
    cmeyer
