"""Run some benchmarks of our current storage system to detect hardware or software related performance issues.

This module is organized around three concepts: test data generation, write/read benchmark functions, and
a JSON-backed benchmark log used to persist and compare results across runs.

Test data is generated by ``create_test_data`` to approximate realistic detector acquisitions using a
``PerformanceTestSettings`` instance, which describes the microscope and detector parameters (beam current,
detector shape, exposure time, collection shape, and sequence length) used to compute a realistic count
distribution. Each benchmark function (for example ``write_hdf5_uncompressed`` or
``write_hdf5_uncompressed_acquisition_loop``) accepts a ``PerformanceTestSettings`` instance and the generated
test data, performs a timed write or read operation, and records the configuration and elapsed time as a
``LogEntry`` in a ``BenchmarkLog``. Read benchmarks such as ``create_virtual_bf_images`` and
``slice_and_sum_collection_axis`` operate on the file names produced by the write benchmarks and reconstruct
the corresponding ``LogEntry`` from the generated file name via ``LogEntry.from_file_name``.

To run the benchmarks directly, execute this script. The ``__main__`` block creates a ``PerformanceTestSettings``
instance, generates test data, runs the write benchmarks, runs the read benchmarks against the resulting files,
and prints a summary of the results as pandas dataframes via ``BenchmarkLog.as_pandas_dataframe``.

To extend this module with a new test for a different data format (for example, a new file format or
compression scheme), add a new write function following the pattern of ``write_hdf5_uncompressed``: accept a
``PerformanceTestSettings`` instance, the test data, and an optional ``BenchmarkLog``; build a ``LogEntry``
describing the configuration under test; time the relevant operations; log the result via ``BenchmarkLog.log``;
and return the generated file name so it can be passed to the read benchmarks. If the new format requires
additional read-side handling, you will need to change the two read benchmark functions,
``create_virtual_bf_images`` and ``slice_and_sum_collection_axis``.
"""


import dataclasses
import platform
import numpy as np
import numpy.typing
import typing
import time
import math
import os
import h5py
import json
import concurrent.futures
from nion.swift.model import HDF5Handler
from nion.data import DataAndMetadata


@dataclasses.dataclass(kw_only=True, frozen=True)
class PerformanceTestSettings:
    folder: str
    target_chunk_size: int = 240*1024
    # Microscpe settings
    beam_current: float = 30e-12 # A, typical values are a few to a few tens of pA
    detector_shape: tuple[int, ...] = (400, 400) # pixels
    exposure_ms: float = 0.4 # This will change the raw data rate of the microscope, but will also increase compression effectiveness
    collection_shape: tuple[int, ...] = (150, 150)
    sequence_length: int = 1
    clean_up_test_data_files: bool = True


def create_test_data(benchmark_settings: PerformanceTestSettings) -> numpy.typing.NDArray[np.float32]:
    # The following calculations assume a BF disk spread over the entire detector, so the illuminated area will be pi/4 of the detector area
    electrons_per_pixel = benchmark_settings.beam_current / 1.6e-19 * benchmark_settings.exposure_ms * 0.001 / math.prod(benchmark_settings.detector_shape)
    lambda_ = electrons_per_pixel * np.pi / 4.0 # reduce electrons_per_pixel by pi/4 for lambda of the distribution to simulate round aperture in square detector
    test_data_shape = benchmark_settings.detector_shape
    if benchmark_settings.collection_shape:
        test_data_shape = benchmark_settings.collection_shape + test_data_shape
    if benchmark_settings.sequence_length > 1:
        test_data_shape = (benchmark_settings.sequence_length,) + test_data_shape
    random_generator = np.random.default_rng()
    # A normal distribution is a good approximation for a poisson distribution at high values of lambda (> 30).
    # We don't quite satisfy this condition, but for testing compression this will still be good enough, and the speed difference between the two
    # is significant. Also take the absolute of the calculated numbers because a poisson distribution does not produce negative numbers.
    # test_data = random_generator.poisson(lam=lambda_, size=test_data_shape)
    test_data = random_generator.normal(loc=lambda_, scale=np.sqrt(lambda_), size=test_data_shape)
    test_data = np.rint(np.abs(test_data, dtype=np.float32))
    print(f'Generated test data of shape {test_data.shape} and type {test_data.dtype}. Uncompressed size: {test_data.size*test_data.itemsize/1024**3:.1f} GB.')
    return test_data


def get_folder_size(start_path: str = '.') -> int:
    """
    Using os.scandir is more than 100x faster than os.listdir or os.walk combined with calling os.path.getsize on
    each file listed.
    """
    total_size = 0
    with os.scandir(start_path) as it:
        for dir_entry in it:
            if dir_entry.is_file(follow_symlinks=False):
                total_size += dir_entry.stat(follow_symlinks=False).st_size
            else:
                total_size += get_folder_size(dir_entry.path)
    return total_size


def threaded_chunk_write(source: numpy.typing.ArrayLike, target: h5py.Dataset, copy_slices: tuple[slice, ...], executor: concurrent.futures.Executor) -> None:
    copy_slices_extended = copy_slices + tuple([slice(0, i) for i in target.shape[len(copy_slices):]])
    def do_copy(slc: tuple[slice, ...]) -> None:
        target[slc] = source[slc]
    it = target.iter_chunks(copy_slices_extended)
    executor.map(do_copy, it)


def write_acquisition(source: numpy.typing.ArrayLike, target: numpy.typing.ArrayLike, collection_shape: tuple[int, ...], exposure_ms: float, n_threads: int = 1) -> None:
    if n_threads > 1:
        executor = concurrent.futures.ThreadPoolExecutor(max_workers=n_threads)
    update_rate = 1000.0 # ms
    frames_per_update = int(max(1, update_rate//exposure_ms))
    last_position = 0
    collection_size = int(np.prod(collection_shape))
    sections = []
    for i in range(0, collection_size, frames_per_update):
        last_position = i
        last_position_reshaped = np.unravel_index(last_position, collection_shape)
        new_position = min(collection_size, last_position + frames_per_update)
        if new_position == collection_size:
            new_position_reshaped = collection_shape
        else:
            new_position_reshaped = np.unravel_index(new_position, collection_shape)
        copy_slices = tuple([slice(int(last_pos), int(new_pos)) for last_pos, new_pos in zip(last_position_reshaped, new_position_reshaped)])
        # print(copy_slices)
        if copy_slices[-1].stop == 0:
            if n_threads > 1:
                threaded_chunk_write(source, target, copy_slices, executor)
            else:
                target[copy_slices] = source[copy_slices]
            continue
        if len(copy_slices) > 1 and copy_slices[0].stop > copy_slices[0].start:
            temp_slices = (slice(copy_slices[0].start, copy_slices[0].stop), slice(0, target.shape[1]))
            if n_threads > 1:
                threaded_chunk_write(source, target, temp_slices, executor)
            else:
                target[temp_slices] = source[temp_slices]
            temp_slices = (slice(copy_slices[0].stop - 1, copy_slices[0].stop), slice(0, copy_slices[1].stop))
            if n_threads > 1:
                threaded_chunk_write(source, target, temp_slices, executor)
            else:
                target[temp_slices] = source[temp_slices]


@dataclasses.dataclass(kw_only=True, frozen=True)
class LogEntry:
    format: str
    data_shape: tuple[int, ...]
    data_dtype: str
    compression: str | None = None
    filter: str | None = None
    clevel: int | None = None
    chunk_shape: tuple[int, ...] | None = None
    shard_shape: tuple[int, ...] | None = None
    compression_ratio: float | None = None
    n_threads: int = 1
    timestamp: float = dataclasses.field(default_factory=time.time)
    beam_current: float | None = None
    acquisition_time: float | None = None
    aux_data: str | None = None
    system: str = dataclasses.field(default_factory=lambda: platform.uname().node)

    def generate_filename(self, extension: str) -> str:
        return (f'{self.format}_{self.compression if self.compression is not None else "uncompressed"}_'
                f'{self.filter if self.filter is not None else "noshuffle"}_{self.clevel if self.clevel is not None else ""}_'
                f'{"x".join([str(s) for s in self.data_shape])}_{"x".join([str(s) for s in self.chunk_shape]) if self.chunk_shape is not None else "None"}_'
                f'{"{:.0f} pA".format(self.beam_current * 1e12) if self.beam_current is not None else ""}_{self.data_dtype}.{extension}')


    @classmethod
    def from_file_name(cls, filename: str) -> 'LogEntry':
        # Example filename: hdf5_uncompressed_noshuffle__100x100x300x300_1x8x300x300_30 pA_float32.h5
        base_name = os.path.basename(filename)
        name_parts = base_name.split('_')
        format = name_parts[0]
        compression = name_parts[1] if name_parts[1] != 'uncompressed' else None
        filter = name_parts[2] if name_parts[2] != 'noshuffle' else None
        clevel = int(name_parts[3]) if name_parts[3] else None
        data_shape = tuple(int(s) for s in name_parts[4].split('x'))
        chunk_shape = tuple(int(s) for s in name_parts[5].split('x')) if name_parts[5] != 'None' else None
        beam_current_str = name_parts[6]
        beam_current = float(beam_current_str.split()[0]) * 1e-12 if beam_current_str else None
        data_dtype = name_parts[7].split('.')[0]
        return cls(format=format, compression=compression, filter=filter, clevel=clevel,
                   data_shape=data_shape, chunk_shape=chunk_shape, beam_current=beam_current,
                   data_dtype=data_dtype)


class BenchmarkLog:

    def __init__(self, log_file_path: str, append_exisiting: bool = True) -> None:
        self.log_file_path = log_file_path
        self._log: dict[LogEntry, list[float]] = dict()
        try:
            if append_exisiting:
                with open(self.log_file_path) as f:
                    for value in json.load(f).values():
                        log_dict_hashable = dict()
                        for key, log_value in value['log'].items():
                            if isinstance(log_value, list):
                                log_dict_hashable[key] = tuple(log_value)
                            else:
                                log_dict_hashable[key] = log_value
                        self._log[LogEntry(**log_dict_hashable)] = value['times']
        except FileNotFoundError:
            pass

    def log(self, entry: LogEntry, time: float) -> None:
        self._log.setdefault(entry, list()).append(float(time))
        self.flush()

    def flush(self) -> None:
        json_dict = {}
        for key, value in self._log.items():
            entry_hash = hash(key)
            log_dict = dataclasses.asdict(key)
            json_dict[entry_hash] = {'log': log_dict, 'times': value}

        with open(self.log_file_path, 'w') as f:
            json.dump(json_dict, f)

    def as_pandas_dataframe(self, filter: typing.Callable[[typing.Sequence[float]], float]=min) -> 'pandas.DataFrame':
        import pandas
        d = {}
        for i, key_value in enumerate(self._log.items()):
            log_entry = dataclasses.asdict(key_value[0])
            log_entry['time'] = filter(key_value[1])
            d[i] = log_entry
        return pandas.DataFrame.from_dict(d, orient='index')


def write_hdf5_uncompressed(benchmark_settings: PerformanceTestSettings, test_data: numpy.typing.NDArray[typing.Any], benchmark_log: BenchmarkLog | None = None) -> str:
    dset_shape = test_data.shape
    dset_dtype = test_data.dtype

    chunks = HDF5Handler.get_write_chunk_shape_for_data(dset_shape,
                                                        dset_dtype,
                                                        data_descriptor=DataAndMetadata.DataDescriptor(False, len(benchmark_settings.collection_shape), len(benchmark_settings.detector_shape)),
                                                        target_chunk_size=benchmark_settings.target_chunk_size)

    settings = LogEntry(format='hdf5',
                        data_shape=dset_shape,
                        data_dtype=dset_dtype.name,
                        chunk_shape=chunks,
                        acquisition_time=benchmark_settings.sequence_length * math.prod(benchmark_settings.collection_shape) * benchmark_settings.exposure_ms * 0.001,
                        beam_current=benchmark_settings.beam_current)

    fname = settings.generate_filename('h5')
    fullpath = os.path.join(benchmark_settings.folder, fname)
    try:
        os.remove(fullpath)
    except FileNotFoundError:
        pass
    t0 = time.perf_counter()
    hdf5_file = h5py.File(fullpath, 'a')
    t1 = time.perf_counter()
    dataset = hdf5_file.require_dataset("data", shape=dset_shape, dtype=dset_dtype, fillvalue=0, chunks=chunks)
    t2 = time.perf_counter()
    dataset[:] = test_data
    t3 = time.perf_counter()
    hdf5_file.flush()
    t4 = time.perf_counter()
    print(f'Chunk shape: {dataset.chunks}')
    hdf5_file.close()
    del dataset
    del hdf5_file

    times = [t0, t1, t2, t3, t4]
    action = ['Open file', 'Create dataset', 'Write data', 'Flush']
    for i in range(len(times)-1):
        print(f'{action[i]}: {times[i+1] - times[i]:.3g} s')
    size = os.path.getsize(fullpath)
    settings = dataclasses.replace(settings, compression_ratio=round(size / test_data.size / test_data.dtype.itemsize, 2))
    print(f'Size of created file: {size/1024**3:.2g} GB.')
    print(f'Total time: {times[-1] - times[0]:.3g} s.')
    print(f'Acquisition time: {settings.acquisition_time:.2g} s.')
    if benchmark_log:
        benchmark_log.log(settings, times[-1] - times[0])
    return fname


def write_hdf5_uncompressed_acquisition_loop(benchmark_settings: PerformanceTestSettings, test_data: numpy.typing.NDArray[typing.Any], benchmark_log: BenchmarkLog | None = None) -> str:
    dset_shape = test_data.shape
    dset_dtype = test_data.dtype

    chunks = HDF5Handler.get_write_chunk_shape_for_data(dset_shape,
                                                        dset_dtype,
                                                        data_descriptor=DataAndMetadata.DataDescriptor(False, len(benchmark_settings.collection_shape), len(benchmark_settings.detector_shape)),
                                                        target_chunk_size=benchmark_settings.target_chunk_size)

    settings = LogEntry(format='hdf5',
                        data_shape=dset_shape,
                        data_dtype=dset_dtype.name,
                        chunk_shape=chunks,
                        acquisition_time=benchmark_settings.sequence_length * math.prod(benchmark_settings.collection_shape) * benchmark_settings.exposure_ms * 0.001,
                        beam_current=benchmark_settings.beam_current,
                        aux_data='write_in_loop')

    fname = settings.generate_filename('h5')
    fullpath = os.path.join(benchmark_settings.folder, fname)
    try:
        os.remove(fullpath)
    except FileNotFoundError:
        pass
    t0 = time.perf_counter()
    hdf5_file = h5py.File(fullpath, 'a')
    t1 = time.perf_counter()
    dataset = hdf5_file.require_dataset("data", shape=dset_shape, dtype=dset_dtype, fillvalue=0, chunks=chunks)
    t2 = time.perf_counter()
    write_acquisition(test_data, dataset, dset_shape[:2], benchmark_settings.exposure_ms)
    t3 = time.perf_counter()
    hdf5_file.flush()
    t4 = time.perf_counter()
    print(f'Chunk shape: {dataset.chunks}')
    hdf5_file.close()
    del dataset
    del hdf5_file

    times = [t0, t1, t2, t3, t4]
    action = ['Open file', 'Create dataset', 'Write data', 'Flush']
    for i in range(len(times)-1):
        print(f'{action[i]}: {times[i+1] - times[i]:.3g} s')
    size = os.path.getsize(fullpath)
    settings = dataclasses.replace(settings, compression_ratio=round(size / test_data.size / test_data.dtype.itemsize, 2))
    print(f'Size of created file: {size / 1024**3:.2g} GB.')
    print(f'Total time: {times[-1] - times[0]:.3g} s.')
    print(f'Acquisition time: {settings.acquisition_time:.2g} s.')
    print(f'Compression ratio: {settings.compression_ratio:.2f}.')
    if benchmark_log:
        benchmark_log.log(settings, times[-1] - times[0])
    return fname


def create_virtual_bf_images(benchmark_settings: PerformanceTestSettings, file_names: set[str], benchmark_log: BenchmarkLog | None = None):
    # Sum the central part of the detector for each frame in the collection

    for filename in file_names:
        fullpath = os.path.join(benchmark_settings.folder, filename)
        hdf5_file = h5py.File(fullpath, 'r')
        opened_dataset = hdf5_file['data']

        read_log_entry = LogEntry.from_file_name(filename)

        dset = opened_dataset
        dset_shape = dset.shape
        vbf_slices = (..., slice(int(dset_shape[2]*0.25), int(dset_shape[2]*0.75)), slice(int(dset_shape[3]*0.25), int(dset_shape[3]*0.75)))

        t0 = time.perf_counter()
        sliced = dset[vbf_slices]
        t1 = time.perf_counter()
        integrated = np.sum(sliced, axis=(-1, -2))
        t2 = time.perf_counter()

        print(f'Slice data: {t1 - t0:.2f} s\nIntegrate: {t2 - t1:.2f} s.')
        if benchmark_log:
            benchmark_log.log(dataclasses.replace(read_log_entry, aux_data='compute_vbf'), float(t2 - t0))
        hdf5_file.close()


def slice_and_sum_collection_axis(benchmark_settings: PerformanceTestSettings, file_names: set[str], benchmark_log: BenchmarkLog | None = None):
    # Slice and sum along the collection axes
    for filename in file_names:
        fullpath = os.path.join(benchmark_settings.folder, filename)
        hdf5_file = h5py.File(fullpath, 'r')
        opened_dataset = hdf5_file['data']

        read_log_entry = LogEntry.from_file_name(filename)

        dset = opened_dataset
        dset_shape = dset.shape
        collection_slices = (slice(int(dset_shape[0]*0.25), int(dset_shape[0]*0.75)), slice(int(dset_shape[1]*0.25), int(dset_shape[1]*0.75)))

        t0 = time.perf_counter()
        sliced = dset[collection_slices]
        t1 = time.perf_counter()
        integrated = np.sum(sliced, axis=(0, 1))
        t2 = time.perf_counter()

        print(f'Slice data: {t1 - t0:.2f} s\nIntegrate: {t2 - t1:.2f} s.')
        if benchmark_log:
            benchmark_log.log(dataclasses.replace(read_log_entry, aux_data='slice_and_sum_collection'), float(t2 - t0))
        hdf5_file.close()


def clean_up_test_data_files(benchmark_settings: PerformanceTestSettings, file_names: set[str]):
    for file_name in file_names:
        try:
            os.remove(os.path.join(benchmark_settings.folder, file_name))
        except FileNotFoundError:
            pass


if __name__ == '__main__':
    write_benchmark_log = BenchmarkLog(os.path.expanduser('~/write_benchmark_chunks_log.json'), append_exisiting=False)
    read_benchmark_log = BenchmarkLog(os.path.expanduser('~/read_benchmark_chunks_log.json'), append_exisiting=False)

    test_settings = PerformanceTestSettings(folder=os.path.expanduser('~'))
    test_data = create_test_data(test_settings)

    test_file_names = {
        write_hdf5_uncompressed(test_settings, test_data, write_benchmark_log),
        write_hdf5_uncompressed_acquisition_loop(test_settings, test_data, write_benchmark_log)
    }

    create_virtual_bf_images(test_settings, test_file_names, read_benchmark_log)
    slice_and_sum_collection_axis(test_settings, test_file_names, read_benchmark_log)

    if test_settings.clean_up_test_data_files:
        clean_up_test_data_files(test_settings, test_file_names)

    print('\nWrite benchmark results:')
    print(write_benchmark_log.as_pandas_dataframe()[['format', 'data_shape', 'data_dtype', 'compression', 'filter', 'clevel', 'chunk_shape', 'compression_ratio', 'n_threads', 'beam_current', 'aux_data', 'system', 'acquisition_time', 'time']])
    print('\nRead benchmark results:')
    print(read_benchmark_log.as_pandas_dataframe()[['format', 'data_shape', 'data_dtype', 'compression', 'filter', 'clevel', 'chunk_shape', 'compression_ratio', 'n_threads', 'beam_current', 'aux_data', 'system', 'time']])
